spring:
  application:
    name: discovery-service
  cloud:
    config:
      server:
        native:
          search-locations: file:/app/config
  eureka:
    client:
      service-url:
        defaultZone: http://discovery:8761/eureka/

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
