spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:*"
              - "https://monapp.com"
              - "https://*.monapp.com"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: product-service
          uri: http://product-service:8090
          predicates:
            - Path=/api/products/**
        - id: product-details-service
          uri: http://product-service:8090
          predicates:
            - Path=/api/product-details/**
        - id: supplier-service
          uri: http://supplier-service:8091
          predicates:
            - Path=/api/suppliers/**
        - id: raw-material-service
          uri: http://raw-material-service:8092
          predicates:
            - Path=/api/raw-materials/**
        - id: raw-material-details-service
          uri: http://raw-material-service:8092
          predicates:
            - Path=/api/raw-material-details/**

server:
  port: 8222

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
