server:
  port: 8091

spring:
  data:
    mongodb:
      username: admin
      password: admin
      host: mongo
      port: 27017
      database: supplier
      authentication-database: admin

  kafka:
    bootstrap-servers: kafka:9092

    # Configuration Producer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        delivery.timeout.ms: 30000
        request.timeout.ms: 15000
        max.block.ms: 10000
        retries: 3
        acks: 1

    # Configuration Consumer
    consumer:
      group-id: supplier-service-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.kclassic.supplier.dto.RawMaterialEvent

#eureka:
#  client:
#    service-url:
#      defaultZone: http://discovery:8761/eureka/
#  instance:
#    prefer-ip-address: false
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus  # Endpoints exposés
  endpoint:
    prometheus:
      access: unrestricted  # Prometheus peut accéder sans auth
  prometheus:
    metrics:
      export:
        enabled: true